title: Exa Heydemans
logo: /assets/img/profile_picture.png
description: Engineer | AI / Data Scientist | Earth science enthusiast
# show_downloads: true
goog/le_analytics:
theme: jekyll-theme-minimal
